version: '3.8'

services:
  # База данных
  db:
    image: postgres:13
    container_name: furniswap_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: furni_swap
    volumes:
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./backend/migrations/init2.sql:/docker-entrypoint-initdb.d/02-init2.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d furni_swap'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5431:5432"
    networks:
      - internal

  # Бэкенд
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: furni_swap_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: furni_swap
      JWT_SECRET_KEY: your_secret_key_change_in_production
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/env.txt:/app/.env
    networks:
      - internal
    restart: unless-stopped

  # Фронтенд
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: furni_swap_frontend
    depends_on:
      - backend
    networks:
      - internal

  # Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: furni_swap_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/uploads:/uploads
    depends_on:
      - backend
      - frontend
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge

volumes:
  postgres_data: 